  services:
    database:
      image: postgres:18-alpine
      container_name: clinicamedica_database
      ports:
        - ${DB_EXTERNAL_PORT}:${DB_PORT}
      restart: always
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - postgres-data:/var/lib/postgresql/data

  volumes:
    postgres-data:
      external: false
